module:
  admin_toolbar: 0
  basic_auth: 0
  block: 0
  breakpoint: 0
  brilleappen: 0
  dblog: 0
  dynamic_page_cache: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  geolocation: 0
  hal: 0
  image: 0
  imce: 0
  node: 0
  page_cache: 0
  rest: 0
  restui: 0
  serialization: 0
  system: 0
  text: 0
  toolbar: 0
  update: 0
  user: 0
  views: 0
  views_ui: 0
  minimal: 1000
theme:
  stark: 0
  stable: 0
  classy: 0
  seven: 0
  brilleappen: 0
  brilleappen_theme: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
