resources:
  'entity:node':
    GET:
      supported_formats:
        - hal_json
        - json
        - xml
      supported_auth:
        - basic_auth
    POST:
      supported_formats:
        - hal_json
      supported_auth:
        - basic_auth
  'entity:menu':
    GET:
      supported_formats:
        - json
        - hal_json
        - xml
      supported_auth:
        - basic_auth
        - cookie
link_domain: null
_core:
  default_config_hash: E9VXRiWZNet4YVBv8j9WQmTlgb-rOjo0MiCSdgV0Guw
